### PR TITLE
Pass field params through sqlalchemy using unexisting dialect

### PR DESCRIPTION
**Pull request by ivanovart**
Use `pydantic_` prefixed arguments to `sa.Column` to  pass them to `pydantic.Field`

### CODE REVIEW

**Comment by ggabriel96** [comment]
Hi there! I didn't see this PR before opening an issue (https://github.com/tiangolo/pydantic-sqlalchemy/issues/30) :sweat_smile: 

This is very nice! It looks very straightforward to define those attributes directly in the `Column` :)
It just got me wondering if it's appropriate to define a dialect just for that. I thought about using the attributes that already exist for a SQLAlchemy `Column` whenever possible, and then the [`info`](https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Column.params.info) attribute for everything else (like `min_length`, `regex`, etc).

**Comment by ivanovart** [comment]
Hey 👋 
I missed the `info` argument, it can be used indeed.
As for dialect I think it's safe to use unless you try to connect to db using `pydantic://` schema

**Comment by sunshine-joe** [comment]
hi, I want to know will this feature  be merged? thanks

**Comment by ggabriel96** [comment]
> hi, I want to know will this feature be merged? thanks

Hey @sunshine-joe, Sebastián Ramírez released a new project based on SQLAlchemy and Pydantic models, [SQLModel](https://github.com/tiangolo/sqlmodel), so I don't think there is a need to maintain this one.

**Pull request closed without merging**
